# Generated by Django 3.0 on 2024-05-13 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tilemodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tilemodel',
            name='url_link',
        ),
    ]
