# Generated by Django 3.0 on 2024-05-13 19:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_auto_20240513_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='tilemodel',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tilemodel',
            name='url_link',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
